### ISSUE TITLE
crash issue

### ISSUE THREAD

**Issue by mdsalah990** [opentok/accelerator-sample-apps-ios#10]
app is cashed when try to refresh OpenTok Playground or disconnect internet while streaming 
but if we disable audio before refresh page or  disconnect internet it works fine

<img width="426" alt="screen shot 2017-12-08 at 7 11 23 pm" src="https://user-images.githubusercontent.com/29517473/33776964-b7f9397c-dc4b-11e7-8d9a-048a6d26a5c9.png">

**Comment by robjperez** [comment]
Hi!

Thanks for reporting the issue. It is now fixed in master branch.
If you are using Accelerator Pack core, please upgrade to 1.1.6 version.
