### ISSUE TITLE
Sample Swift Project Build Error ( Swift4, XCode10)

### ISSUE THREAD

**Issue by thomas4Bitcraft** [opentok/accelerator-sample-apps-ios#12]
## New issue checklist
Swift Sample Project Build Error

### General information

- Library version(s): master
- iOS version: Swift4
- XCode version: 10
- Devices/Simulators/Machine affected: All
- Reproducible in the demo project? (Yes/No):  Yes
- Related issues:

#### Expected behavior

`Pod install` fetches the framework and I can build project 

#### Actual behavior

I can not build the Project in Xcode 10 and Swift 4

#### Steps to reproduce

- Download Sample Project
- `pod install`
- Go in Workspace
- Build the project

#### Crash log? Screenshots? Videos? Sample project?

`Showing Recent Messages

Prepare build
note: Using new build systemnote: Planning buildnote: Constructing build description

Build system information

**ERROR 1-3:**

warning: duplicate output file '/Users/<username>/Library/Developer/Xcode/DerivedData/AcceleratorSampleApp-Swift-gfaqeotdedgyaoenlfxtncisxwms/Build/Products/Debug-iphoneos/OTTextChatAccelerator/OTTextChatAcceleratorBundle.bundle/Info.plist' on task: ProcessInfoPlistFile /Users/<username>/Library/Developer/Xcode/DerivedData/AcceleratorSampleApp-Swift-gfaqeotdedgyaoenlfxtncisxwms/Build/Products/Debug-iphoneos/OTTextChatAccelerator/OTTextChatAcceleratorBundle.bundle/Info.plist /Users/<username>/Downloads/accelerator-sample-apps-ios-master/AcceleratorSampleApp-Swift/Pods/Target Support Files/OTTextChatAccelerator/ResourceBundle-OTTextChatAcceleratorBundle-Info.plist (in target 'OTTextChatAccelerator-OTTextChatAcceleratorBundle')
Build system information
warning: duplicate output file '/Users/<username>/Library/Developer/Xcode/DerivedData/AcceleratorSampleApp-Swift-gfaqeotdedgyaoenlfxtncisxwms/Build/Products/Debug-iphoneos/OTAcceleratorCore/OTAcceleratorCoreBundle.bundle/Info.plist' on task: ProcessInfoPlistFile /Users/<username>/Library/Developer/Xcode/DerivedData/AcceleratorSampleApp-Swift-gfaqeotdedgyaoenlfxtncisxwms/Build/Products/Debug-iphoneos/OTAcceleratorCore/OTAcceleratorCoreBundle.bundle/Info.plist /Users/<username>/Downloads/accelerator-sample-apps-ios-master/AcceleratorSampleApp-Swift/Pods/Target Support Files/OTAcceleratorCore/ResourceBundle-OTAcceleratorCoreBundle-Info.plist (in target 'OTAcceleratorCore-OTAcceleratorCoreBundle')
Build system information
warning: duplicate output file '/Users/<username>/Library/Developer/Xcode/DerivedData/AcceleratorSampleApp-Swift-gfaqeotdedgyaoenlfxtncisxwms/Build/Products/Debug-iphoneos/OTAnnotationAccelerator/OTAnnotationAcceleratorBundle.bundle/Info.plist' on task: ProcessInfoPlistFile /Users/<username>/Library/Developer/Xcode/DerivedData/AcceleratorSampleApp-Swift-gfaqeotdedgyaoenlfxtncisxwms/Build/Products/Debug-iphoneos/OTAnnotationAccelerator/OTAnnotationAcceleratorBundle.bundle/Info.plist /Users/<username>/Downloads/accelerator-sample-apps-ios-master/AcceleratorSampleApp-Swift/Pods/Target Support Files/OTAnnotationAccelerator/ResourceBundle-OTAnnotationAcceleratorBundle-Info.plist (in target 'OTAnnotationAccelerator-OTAnnotationAcceleratorBundle')
Build system information
error: Multiple commands produce '/Users/<username>/Library/Developer/Xcode/DerivedData/AcceleratorSampleApp-Swift-gfaqeotdedgyaoenlfxtncisxwms/Build/Products/Debug-iphoneos/OTTextChatAccelerator/OTTextChatAcceleratorBundle.bundle/Info.plist':
1) Target 'OTTextChatAccelerator-OTTextChatAcceleratorBundle' (project 'Pods') has copy command from '/Users/<username>/Downloads/accelerator-sample-apps-ios-master/AcceleratorSampleApp-Swift/Pods/OTTextChatAccelerator/OTTextChatAcceleratorBundle/Info.plist' to '/Users/<username>/Library/Developer/Xcode/DerivedData/AcceleratorSampleApp-Swift-gfaqeotdedgyaoenlfxtncisxwms/Build/Products/Debug-iphoneos/OTTextChatAccelerator/OTTextChatAcceleratorBundle.bundle/Info.plist'
2) Target 'OTTextChatAccelerator-OTTextChatAcceleratorBundle' (project 'Pods') has process command with output '/Users/<username>/Library/Developer/Xcode/DerivedData/AcceleratorSampleApp-Swift-gfaqeotdedgyaoenlfxtncisxwms/Build/Products/Debug-iphoneos/OTTextChatAccelerator/OTTextChatAcceleratorBundle.bundle/Info.plist'

Build system information
error: Multiple commands produce '/Users/<username>/Library/Developer/Xcode/DerivedData/AcceleratorSampleApp-Swift-gfaqeotdedgyaoenlfxtncisxwms/Build/Products/Debug-iphoneos/OTAnnotationAccelerator/OTAnnotationAcceleratorBundle.bundle/Info.plist':
1) Target 'OTAnnotationAccelerator-OTAnnotationAcceleratorBundle' (project 'Pods') has copy command from '/Users/<username>/Downloads/accelerator-sample-apps-ios-master/AcceleratorSampleApp-Swift/Pods/OTAnnotationAccelerator/OTAnnotationAcceleratorBundle/Info.plist' to '/Users/<username>/Library/Developer/Xcode/DerivedData/AcceleratorSampleApp-Swift-gfaqeotdedgyaoenlfxtncisxwms/Build/Products/Debug-iphoneos/OTAnnotationAccelerator/OTAnnotationAcceleratorBundle.bundle/Info.plist'
2) Target 'OTAnnotationAccelerator-OTAnnotationAcceleratorBundle' (project 'Pods') has process command with output '/Users/<username>/Library/Developer/Xcode/DerivedData/AcceleratorSampleApp-Swift-gfaqeotdedgyaoenlfxtncisxwms/Build/Products/Debug-iphoneos/OTAnnotationAccelerator/OTAnnotationAcceleratorBundle.bundle/Info.plist'

Build system information
error: Multiple commands produce '/Users/<username>/Library/Developer/Xcode/DerivedData/AcceleratorSampleApp-Swift-gfaqeotdedgyaoenlfxtncisxwms/Build/Products/Debug-iphoneos/OTAcceleratorCore/OTAcceleratorCoreBundle.bundle/Info.plist':
1) Target 'OTAcceleratorCore-OTAcceleratorCoreBundle' (project 'Pods') has copy command from '/Users/<username>/Downloads/accelerator-sample-apps-ios-master/AcceleratorSampleApp-Swift/Pods/OTAcceleratorCore/OTAcceleratorCoreBundle/Info.plist' to '/Users/<username>/Library/Developer/Xcode/DerivedData/AcceleratorSampleApp-Swift-gfaqeotdedgyaoenlfxtncisxwms/Build/Products/Debug-iphoneos/OTAcceleratorCore/OTAcceleratorCoreBundle.bundle/Info.plist'
2) Target 'OTAcceleratorCore-OTAcceleratorCoreBundle' (project 'Pods') has process command with output '/Users/<username>/Library/Developer/Xcode/DerivedData/AcceleratorSampleApp-Swift-gfaqeotdedgyaoenlfxtncisxwms/Build/Products/Debug-iphoneos/OTAcceleratorCore/OTAcceleratorCoreBundle.bundle/Info.plist'

**Error 4:**

![image](https://user-images.githubusercontent.com/44415527/47430750-815b9b80-d79a-11e8-9f30-41108b54780c.png)

Build failed    24.10.18, 14:27    0.3 seconds

## Question or Feature Request

Hello Opentok-Team,

We are a subscribed user of your service and already built an webapp for our customers. We wanted to create an iOS App now but unfortunately we can't build your sample project so we are not able to continue our work. It would be great if anyone of you could look into this issue!

Best

**Comment by igorkravchenko** [comment]
Same issue for me. Please advise.

**Comment by MichaelJolley** [comment]
This should be resolved. If you continue to have a problem, feel free to open a new issue.
