### ISSUE TITLE
Need your help for implementing annotation

### ISSUE THREAD

**Issue by blsepandi** [opentok/accelerator-sample-apps-ios#14]
We want to call function " fileprivate func startAnnotation() " from  ScreenShareViewController.swift class.
When we are trying to call we getting Fatal  error "Fatal error: Attempted to read an unowned reference but the object was already deallocated"
please help on this.  we want to implement Annotation.

**Comment by msach22** [comment]
@blsepandi Thanks for filing an issue.  Could you please elaborate where you're calling this method from? As you can see, it's a method that's only accessible within the file and is being called when the `.publisherCreated` signal is received.

Please note that this is just a sample, you would need to build your own custom implementation using this sample as reference.

**Comment by blsepandi** [comment]
Toxbox team suggested us to use objective c code. We have used object-C sample code. The code is working fine. 
This application one way annotation from publisher to subscriber. In our business requirement we need to make annotation on both side(From publisher to Subscriber and Subscriber to Publisher).
Can you please help how to implement annotation on both side in iOS platform.

**Comment by msach22** [comment]
@blsepandi Thanks for updating me. This app is just a sample on how to do add annotations, but you would need to build it out yourself if you want to do custom things. 

I'll be happy to take a PR with improvements 😄

**Comment by blsepandi** [comment]
Now we are able to do annotation on both publisher & subscriber side. 
We have one query about this when publisher making annotation line, it's rendering normal and subscriber is also able to receive as it is.

But when subscriber is trying the same annotation in the same call, then rendering of line is regular at subscriber side and dotted line is rendering at publisher side which seems to us that its functionality to make difference between the publisher & subscribers annotating lines hence

Manik, Can you please confirm the same that its functionality (NOT AN ISSUE) or let me know if i'm wrong here.

**Comment by MichaelJolley** [comment]
Hi @blsepandi, are you still experiencing this problem?

**Comment by MichaelJolley** [comment]
Closing this issue as stale. Feel free to re-open if the problem still exists.
