### ISSUE TITLE
Opentok Screen Sharing Crashing Sometimes

### ISSUE THREAD

**Issue by blsepandi** [opentok/accelerator-sample-apps-ios#15]
## Opentok Screen Sharing Crashing sometimes

- [x] I have read all of the [`README`](https://github.com/opentok/accelerator-core-ios/blob/master/README.md) 
- [x] I have searched [existing issues](https://github.com/opentok/accelerator-core-ios/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):
pod 'OTTextChatAccelerator', '1.0.4'
pod 'OTAnnotationAccelerator', '= 1.0.0-beta2'
pod 'SVProgressHUD', '=2.2.1'
pod 'OTAcceleratorCore', '= 1.1.6'

- iOS/Android/Browser version(s):
iOS 12.1

- Devices/Simulators/Machine affected:
Device / Simulator

- Reproducible in the demo project? (Yes/No): 
YES, Sometimes while screen sharing

- Related issues:
App Crashing Error - Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior. Issue, Raised with Opentok Ticket Number 29930

#### Expected behavior

> It should properly handle stop capturing the screen

#### Actual behavior

> Sometimes its getting crash

#### Steps to reproduce

> Go to screen capture window and do long or short wait or operation

#### Crash log? Screenshots? Videos? Sample project?

>OTScreenCapture.m only as some times very rare we are getting crash (in sample app also) in to one block of code while stopping screen capturing with below mentioned errors

- (int32_t)stopCapture
{
    _capturing = NO;
    
    dispatch_sync(_queue, ^{
        if (_timer) {
            dispatch_source_cancel(_timer);
        }
    });
    
    return 0;
}
![M2](https://user-images.githubusercontent.com/6635525/57292018-5c979780-70de-11e9-9d82-7e0cbbe0d0cf.png)

>Error - Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior

## Question or Feature Request

> Issue, Raised with Opentok Ticket Number 29930

**Comment by MichaelJolley** [comment]
Hi @blsepandi, are you still experiencing this? We've recently updated our samples.

**Comment by MichaelJolley** [comment]
Closing this issue as stale. Feel free to re-open if the problem still exists.
