### ISSUE TITLE
OTAnnotationKit repository not found

### ISSUE THREAD

**Issue by jimmyleetranzport** [opentok/accelerator-sample-apps-ios#7]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/opentok/accelerator-core-ios/blob/master/README.md) 
- [x] I have searched [existing issues](https://github.com/opentok/accelerator-core-ios/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):
- iOS/Android/Browser version(s):
- Devices/Simulators/Machine affected:
- Reproducible in the demo project? (Yes/No): 
- Related issues:

## Bug report
Cocoapod installation failed.

#### Expected behavior

> ...  $ pod install

#### Actual behavior

$ pod install

Analyzing dependencies
Downloading dependencies
Installing LHToolbar (1.3.0-beta)
Installing OTAcceleratorCore (1.0.5)
Installing OTAcceleratorPackUtil (2.0.8)

[!] Error installing OTAcceleratorPackUtil
[!] /usr/bin/git clone https://github.com/opentok/acc-pack-common.git /var/folders/jz/1yy4vh8x7tq1tbtxy8jnghv00000gn/T/d20170420-960-1tll7ba --template= --single-branch --depth 1 --branch 2.0.8

Cloning into '/var/folders/jz/1yy4vh8x7tq1tbtxy8jnghv00000gn/T/d20170420-960-1tll7ba'...
remote: Repository not found.
fatal: repository 'https://github.com/opentok/acc-pack-common.git/' not found

[!] Smart quotes were detected and ignored in your Podfile. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.

## Question or Feature Request

> ... Annotation repository is removed?
Then, how can we check this OpenTok iOS SDK sample?

Thank you

**Comment by Lucashuang0802** [comment]
@jimmyleetranzport thx, the error caused by our repo migration. It will be updated shortly. 😃

**Comment by Lucashuang0802** [comment]
@jimmyleetranzport, sorry for taking a bit longer. I have updated the `Podfile`. 😃

**Comment by sbuxar** [comment]
Hey Lucashuang,

I'm still getting the same error after using username and password. 
Could you please suggest your input here?

Thanks!

**Comment by dtsMithun** [comment]
Still getting Error:
[!] Error installing OTAcceleratorPackUtil
[!] /usr/bin/git clone https://github.com/opentok/acc-pack-common.git /var/folders/v5/ln6dq7f55cvf3t63p4vknyzr0000gn/T/d20200827-37570-1c9r9yw --template= --single-branch --depth 1 --branch 2.0.8

Cloning into '/var/folders/v5/ln6dq7f55cvf3t63p4vknyzr0000gn/T/d20200827-37570-1c9r9yw'...
remote: Repository not found.
fatal: repository 'https://github.com/opentok/acc-pack-common.git/' not found

Please help me
